config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  resources :carts
  resources :information do
    get "search", on: :collection
    resources :reviews
  end
  
  devise_for :users, controllers: {
    registrations: 'registrations'
  }
  
  
  root 'information#index'
end

app/models/information.rb
class Information < ApplicationRecord
  before_destroy :not_referenced_by_any_line_item
  mount_uploaders :image, ImageUploader
  serialize :image, JSON
  has_many :line_items
  belongs_to :user, optional: true
  has_many :reviews,dependent: :destroy
  validates :title, presence: true
  validates :description, length: { maximum: 1000, too_long: "%{count} characters is the maximum
  allowed."}
  validates :title, length: { maximum: 140, too_long: "%{count} characters is the maximum
  allowed."}
  CONDITION = %w{ New Fair Poor }
  
  
  
  class << self
    def search(query)
      rel = order("id")
      if query.present?
        rel = rel.where("title LIKE ? OR description LIKE ?",
          "%#{query}%", "%#{query}%")
      end
      rel
    end
  end
  
   

  
  private
  
  def not_referenced_by_any_line_item
    unless line_items.empty?
      errors.add(:base, "Line items present")
      throw :abort
    end
  end
end

app/controllers/information_controller.rb
class InformationController < ApplicationController
  before_action :set_information, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  # GET /information
  # GET /information.json
  def index
     @informations = Information.order("id")
  end

  # GET /information/1
  # GET /information/1.json
  def show
  end

  # GET /information/new
  def new
    @information = current_user.informations.build
  end

  # GET /information/1/edit
  def edit
  end

  # POST /information
  # POST /information.json
  def create
    @information = current_user.informations.build(information_params)
    respond_to do |format|
      if @information.save
        format.html { redirect_to @information, notice: 'Information was successfully created.' }
        format.json { render :show, status: :created, location: @information }
      else
        format.html { render :new }
        format.json { render json: @information.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /information/1
  # PATCH/PUT /information/1.json
  def update
    respond_to do |format|
      if @information.update(information_params)
        format.html { redirect_to @information, notice: 'Information was successfully updated.' }
        format.json { render :show, status: :ok, location: @information }
      else
        format.html { render :edit }
        format.json { render json: @information.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /information/1
  # DELETE /information/1.json
  def destroy
    @information.destroy
    respond_to do |format|
      format.html { redirect_to information_index_url, notice: 'Information was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def search
    @informations = Information.search(params[:q])
    render "index"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_information
      @information = Information.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def information_params
      params.require(:information).permit(:condition, :title, :description, {image: [] })
    end
    
     
end

app/helpers/information_helper.rb
module InformationHelper
  def information_author(information)
    user_signed_in? && current_user.id == information.user_id
  end
end

app/views/information/_form.html.erb
<div class="columns">
  <div class="column is-8 is-centered">

    <%= simple_form_for @information, html: { multipart: true } do |f| %>
      <%= f.error_notification %>

        <div class="columns">
          <div class="field column is-9">
            <div class="control">
              
              
              <%= f.input :title , required: true, input_html: { class: "input"}, wrapper: false, label_html: { class:"label"}, label: "Title(year,college,class)" %>
            </div>
          </div>
        </div>

         

        <div class="field">
          <div class="control">
              <%= f.input :description, required: true, input_html: { class: "input" }, wrapper: false, label_html: { class:"label" } %>
          </div>
        </div>

         
           
        <div class="columns">
          <div class="field column is-4">
            <div class="control">
              <label class="label">Condition</label>
              <div class="control has-icons-left">
                <span class="select">
                  <%= f.input_field :condition, collection: Information::CONDITION, prompt: "Select condition" %>
                </span>
                <span class="icon is-small is-left">
                  <i class="fa fa-paint-brush"></i>
                </span>
              </div>
            </div>
          </div>
        </div>

         <div class="field">
          <div class="control">
            <label class="label">Add images(パソコンだとcommandを押しながら選択すると複数指定できます）</label>
              <div class="file">
              <label class="file-label">
                <%#= f.input :image, as: :file, input_html: { class:"file-input instrument-image" }, label: false, wrapper: false, :multiple => true %>
                <%#= f.input :image, as: :file, input_html: { class:"file-input instrument-image" }, label: false, wrapper: false, :multiple => true %>
                  <%= f.file_field :image, multiple: true%>
                  <div id="result"></div>
              </label>
              </div>
            </div>
          </div>
          <output id="list"></output>
        <hr />

        <div class="field is-grouped">
          <div class="control">
            <%= f.button :submit, class: 'button is-warning' %>
            <%= link_to 'Cancel', information_index_path, class:'button is-light' %>
          </div>
        </div>

      <% end %>
  </div>
</div>

app/views/information/edit.html.erb
<% content_for :header do %>
<section class="hero is-warning">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Editing Instrument
      </h1>
    </div>
  </div>
</section>
<% end %>

<div class="pv4">
  <%= render 'form', information: @information %>
</div>

app/views/information/index.html.erb
<% content_for :header do %>
<section class="hero is-warning">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Browse the latest test information
      </h1>
      <p>
        user数が増えたら将来的に投稿者に利益が出る仕組みにしたいと思います。
      </p>
      <p>
        <a href="https://youtu.be/DarjUgCCTKg">『使い方』（クリックしてください）</a>
        
      </p>
      <%= form_tag :search_information_index, method: :get, class: "search" do %>
        <%= text_field_tag "q", params[:q] %>
        <%= submit_tag "検索" %>
      <% end %>
      
      
    </div>
  </div>
</section>
<% end %>
<div class="instrument-index-grid pt4">
  <% if @informations.present? %>
    <% @informations.each do |information| %>
  
      <div class="instrument border-light">
        <div class="instrument-thumb">
          
        
        <% if information.image.present? %>
          <div class="feature-image">
             
              <%= link_to image_tag(information.image.first.url(:thumb)), information %>
              
            
          </div>
        <% end %>
        
  
        <% if information.condition? %>
          <div class="condition">
            <span class="tag is-dark"><%= information.condition %></span>
          </div>
        <% end %>
        </div>
  
  
      <div class="pa3">
  
        <h3 class="fw7 f4 title"><%= link_to information.title, information %></h3>
  
        <p class="has-text-gray fg pt1">Post by <%= information.user.name %></p>
  
  
        <% if information_author(information) %>
           <%= link_to 'Edit', edit_information_path(information), class: "button is-small" %>
           <%= link_to 'Delete', information, method: :delete, data: { confirm: "Are you sure ?" }, class: "button is-small" %>
        <% end %>
  
      </div>
    </div>
    <% end %>
  <% end %>
</div>

app/views/information/new.html.erb
<% content_for :header do %>
<section class="hero is-warning">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
         post an test information
      </h1>
    </div>
  </div>
</section>
<% end %>

<div class="pv4">
  <%= render 'form', information: @information %>
</div>

app/views/information/show.html.erb
<% content_for :body_class, 'bg-light' %>

<section class="section instrument-show">
  <div class="columns">
    <div class="column is-8">
      <h1 class="title is-2"><%= @information.title %></h1>

      <ul class="pv1">
        <% if @information.condition? %>
        <li class="inline-block pr3"><%= @information.condition %></li>
        <% end %>
      </ul>

       
        <% if @information.image.present? %>
          <div class="feature-image">
            <% @information.image.each do |image| %>
              <%= image_tag(image.url) %>
            <% end %>
          </div>
        <% end %>
      

      <div class="content pa4 mt3 bg-white border-radius-3">

      <h3 class="subtitle is-4">Description</h3>
      <%= @information.description %>


      <h3 class="subtitle is-4 pt5">Product Specs</h3>

      <table class="table is-narrow">
        <% if @information.condition %>
        <tr>
          <td class="has-text-weight-bold">Condition:</td>
          <td><%= @information.condition %></td>
        </tr>
        <% end %>

      </table>
    </div>
    </div>
    <div class="column is-3 is-offset-1">
      <div class="bg-white pa4 border-radius-3">
        <p class="has-text-centered mb4">Post by <%= @information.user.name %></p>
        <%= button_to 'Add to cart', line_items_path(information_id: @information), class: 'button is-warning add-to-cart' %>
      </div>
      
      <div class="reviews">
        <h1>Send thanks</h1>
        <%= render @information.reviews %>
        <div>
          <%= link_to "Say thank you", new_information_review_path(@information), class: "btn-custom" %>
        </div>
      </div>
    </div>
  </div>

  <% if information_author(@information) %>
    <%= link_to 'Edit', edit_information_path(@information), class: 'button' %>
  <% end %>
</section>