config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  resources :carts
  resources :information do
    get "search", on: :collection
    resources :reviews
  end
  
  devise_for :users, controllers: {
    registrations: 'registrations'
  }
  
  
  root 'information#index'
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_information
  before_action :find_review, only: [:edit,:update, :destroy]
  def new
    @review = Review.new
  end
  
  def create
    @review = Review.new(review_params)
    @review.information_id = @information.id
    @review.user_id = current_user.id
    
    if @review.save
      redirect_to information_path(@information)
    else
      reder 'new'
    end
  end
  
  def edit
    
  end
  
  def update
    
    if @review.update(review_params)
      redirect_to information_path(@information)
    else
      render 'edit'
    end
  end
  
  def destroy
    @review.destroy
    redirect_to information_path(@information)
  end
  
  private
  
  def review_params
    params.require(:review).permit(:comment)
  end
  
  def find_information
    @information = Information.find(params[:information_id])
  end
  
  def find_review
    @review = Review.find(params[:id])
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= simple_form_for([@information, @information.reviews.build]) do |f| %>
  <%= f.input :comment , required: true, input_html: { class: "input"}, wrapper: false, label_html: { class:"label"}, label: "Say thank you" %>
  <%= f.button :submit, :class => "btn-custom2" %>
<% end %>

app/views/reviews/_review.html.erb
<div class="review">
	<p class="review-comment"><%= review.comment %></p>
	<%if user_signed_in? %>
	  <% if review.user_id == current_user.id %>
			<div class="links btn-group">
				<%= link_to "Edit", edit_information_review_path(review.information, review), class: "btn btn-custom" %>
				<%= link_to "Delete", information_review_path(review.information, review), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-custom" %>
			</div>
		<% end %>
	<% end %>
</div>	

app/views/reviews/edit.html.erb
<div class="col-md-6 col-md-offset-3">

	<div class="edit-review-form">

		 

		<%= simple_form_for([@information, @review]) do |f| %>
			<%= f.input :comment , required: true, input_html: { class: "input"}, wrapper: false, label_html: { class:"label"}, label: "Say thank you" %>
			<%= f.button :submit, :class => "btn-custom2" %>
		<% end %>	

	</div>

</div>

app/views/reviews/new.html.erb
<%= render 'form' %>